### ISSUE TITLE
Delete branch when PR is closed

### ISSUE THREAD

**Issue by k3nsei** [googleapis/release-please#753] opened 2021-02-07 00:12 UTC
When bot is closing PR branch is still there. It would be nice to remove branch related to this PR.

**Comment by bcoe** [comment] 2021-02-08 21:59
@k3nsei we're in the process of moving towards a stable branch name, rather than creating a branch for each release. Would this solve the problem for you? (we still wouldn't automatically delete that one branch, but we'd always be reusing it).

**Comment by k3nsei** [comment] 2021-02-08 22:06
Yeah that sounds reasonable. Because there is an option to automatically delete merged branches.

**Comment by codyoss** [comment] 2021-07-22 16:51
This seems like a dupe of #212.

**Comment by bcoe** [comment] 2021-07-28 19:45
Closing in favor of #212 👍

**Closed** 2021-07-28 19:44 UTC
Labels: type: feature request
