### ISSUE TITLE
Using "release-as" adds spam entries to CHANGELOG

### ISSUE THREAD

**Issue by bcoe** [googleapis/release-please#1210] opened 2022-01-12 17:09 UTC
👇 it appears that using `release-as` results in adding the entry `v0.3.0` to the changelog.

![Screenshot 2022-01-12 11 31 53 AM](https://user-images.githubusercontent.com/194609/149187995-f81b7f45-0a3f-465a-aac2-89a8580e9de2.png)

**Comment by chingor13** [comment] 2022-01-12 23:07
This is happening because we are parsing Release-As commits into the `notes` field with `title`: `RELEASE AS`. We are using conventional-changelog-writer under the hood which is interpreting that note as a BREAKING CHANGE

**Comment by chingor13** [comment] 2022-01-12 23:08
Also, the test snapshot was incorrectly asserting the output for Release-As

**Comment by chingor13** [comment] 2022-01-12 23:26
Duplicate of #1205

**Closed by chingor13** 2022-01-12 23:26 UTC
Labels: priority: p2, type: bug
