### ISSUE TITLE
Many Java monorepo modules have the same release note from java-analytics-data 

### ISSUE THREAD

**Issue by suztomo** [googleapis/release-please#1705] opened 2022-10-14 22:14 UTC
In this release please pull request https://github.com/googleapis/google-cloud-java/pull/8610, the release notes in many modules have these two new features:

> [analyticsdata] add subject_to_thresholding field to ResponseMetadata type (#8545) (8fdc6c1)
> add tokens_per_project_per_hour field to PropertyQuota type (8fdc6c1)

However they are file changes in java-analytics-data module committed in https://github.com/googleapis/google-cloud-java/pull/8545/files. These release notes should only appear in google-analytics-data.

<img width="954" alt="Screen Shot 2022-10-25 at 11 10 43 AM" src="https://user-images.githubusercontent.com/28604/197812138-f1aa977c-8c7a-40d3-8448-c71776eef511.png">

**Comment by chingor13** [comment] 2022-10-27 21:30
This is a bug in how that PR was merged. https://github.com/googleapis/google-cloud-java/commit/8fdc6c1f10f88f30f4d1407579d645f75366b4cf is the offending commit which touches no files. By design, a commit with no files applies to all components (to support forced commit messages like:

```
chore: fix version

Release-As: 1.2.3
```

**Closed by chingor13** 2022-10-27 21:30 UTC
Labels: priority: p2, type: bug

**Comment by suztomo** [comment] 2022-10-27 23:04
Thank you for investigation. I guess it touched no files because the changes were already applied in a previous "[Many APIs]" pull request.

I think this situation is common. We'll see whether this recurs.
