### ISSUE TITLE
Unhelpful "not found" message when running on private repo

### ISSUE THREAD

**Issue by nzakas** [googleapis/release-please#772] opened 2021-02-16 22:34 UTC
#### Environment details

  - OS: Ubuntu 18.04.5 (GitHub Workflow)
  - Node.js version: n/a
  - npm version: n/a
  - `release-please` version: v1.3.0

#### Steps to reproduce

  1. Use the sample `release-please.yml` workflow from the README in a private Node.js repository that has had zero releases so far.
  2. Push a commit to the repository.
  3. Get this output:

```
Run GoogleCloudPlatform/release-please-action@v1.3.0
✖ no recent release PRs found
✔ found 6 commits since undefined
✖ branch release-v1.0.0 already exists
✖ CHANGELOG.md not found
✔ creating CHANGELOG.md
✔ updating package.json from 0.0.0 to 1.0.0
✔ updating package-lock.json from 0.0.0 to 1.0.0
✖ file samples/package.json did not exist
Error: release-please failed: Not Found
```

What does that last "Not Found" mean?

**Comment by bcoe** [comment] 2021-02-17 01:54
@nzakas could I bother you to try running `release-please@v2`, just to see if we're still having the same issue?

**Comment by nzakas** [comment] 2021-02-17 02:02
When I flipped the repo public, the problem went away: https://github.com/humanwhocodes/memory

**Comment by bcoe** [comment] 2021-02-17 06:00
@nzakas sounds like if was likely a permission issue on private repositories.

**Comment by rudywaltz** [comment] 2021-03-01 16:11
this is possible still issue with latest version google-github-actions/release-please-action/issues/262
on my private repo I didn't see this issue, but within the organisation repo I have the same with the latest version

**Comment by bcoe** [comment] 2021-03-01 17:27
@rudywaltz sounds like permission issues, what we can improve is the quality of that error message (which is actually in one of our dependencies I believe).

**Comment by bcoe** [comment] 2021-03-01 17:27
@rudywaltz if you have the cycles, perhaps you could run the CLI version of `release-please` with `--debug` and see if anything jumps out? (it might work because of the different type of token).

**Comment by rudywaltz** [comment] 2021-03-01 17:36
Sadly I think we found the issue our GitHub token was rotated. Just it was too much coincident.
(We use a unique token because we triggering another Action after.

**Comment by bcoe** [comment] 2021-06-22 15:57
_@chingor13 assigning this one over to you, not out of SLO for a month or so._

We could perhaps address this issue when we address https://github.com/googleapis/repo-automation-bots/issues/1636.

**Comment by abeMedia** [comment] 2021-07-24 01:25
I'm having a similar issue. It creates the release PR without a problem, but then when I merge that I get the same message when it's meant to create the releases:

![image](https://user-images.githubusercontent.com/4355715/126853621-6e00823c-91fb-4b74-bcd4-d4abea99ead1.png)

This only seems to be happening on free orgs as I did the same setup on a paid one just earlier today and it worked fine.

**Comment by bcoe** [comment] 2021-08-06 17:39
@abeMedia @nzakas I'm testing on a private repository, using the default `GITHUB_TOKEN`, with the latest version of `release-please`, and I can't seem to get this `Not found` error, I'm using this configuration:

```yml
  on:
    push:
      branches:
        - main
  name: release-please
  jobs:
    release-please:
      runs-on: ubuntu-latest
      steps:
        - uses: GoogleCloudPlatform/release-please-action@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            release-type: go
            package-name: release-please-action
            monorepo-tags: false
            bump-minor-pre-major: false
            clean: true
            fork: false
            pull-request-title-pattern: 'chore${scope}: release${component} ${version}'
```

**Comment by abeMedia** [comment] 2021-08-06 17:45
It's quite strange because I get the error on my own private repos, but not on the ones used at my job. Only difference I can think of is that the ones at my job are GitHub enterprise while mine are free ones.

It creates the release PR no problem but then gas the Not Found error when creating the actual release. The reverted PR fixed it for me though.

**Comment by bcoe** [comment] 2021-08-06 21:35
@abeMedia I'm not fully understanding why this would fix things for you, I would expect that if there's a permission error calling `getFileContentsWithSimpleAPI` there would be a permission error with `getFileContentsWithDataAPI` as well.

Is there a chance that the path to fetch contents is slightly different with an enterprise account?

`GET /repos/:owner/:repo/contents/:path`.

Are you using an Enterprise version of github.com, or is this a self hosted instance?

**Comment by abeMedia** [comment] 2021-08-06 22:20
It's github.com. The enterprise one is the one that works without the fix though. It's my own free private repos that don't work without the fix.

**Comment by bcoe** [comment] 2021-08-09 18:52
@abeMedia I'm testing the configuration:

```js
  on:
    push:
      branches:
        - main
  name: release-please
  jobs:
    release-please:
      runs-on: ubuntu-latest
      steps:
        - uses: GoogleCloudPlatform/release-please-action@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            release-type: go
            package-name: release-please-action
            monorepo-tags: false
            bump-minor-pre-major: false
            clean: true
            fork: false
            pull-request-title-pattern: 'chore${scope}: release${component} ${version}'
```

On my own private repository. I've invited you to [test-release-please-private](https://github.com/bcoe/test-release-please-private) perhaps you can point me towards what's configured differently? Or help me reproduce the issue.

**Comment by bcoe** [comment] 2021-08-09 18:55
@abeMedia perhaps a better idea, would you be able to invite me to a fake private repository that's exhibiting the issue?

**Comment by bcoe** [comment] 2021-08-11 18:03
Closing in favor of https://github.com/googleapis/release-please/issues/1014, this seems to now be happening for one specific edge-case (release-please now supports private repositories).

**Closed by bcoe** 2021-08-11 18:03 UTC
Labels: priority: p2, type: bug, needs more info
