### ISSUE TITLE
Manifest releaser does not update dependent modules

### ISSUE THREAD

**Issue by dyladan** [googleapis/release-please#1032] opened 2021-08-30 20:59 UTC
#### Environment details

  - OS: macos and linux
  - Node.js version: 12, 14, and 16
  - npm version: 6 and 7
  - `release-please` version: 11.22.0

#### Steps to reproduce

  1. Create a lerna monorepo with interdependent modules
  2. Use manifest releaser to create a release

See an example of a broken PR here: https://github.com/open-telemetry/opentelemetry-js/pull/2444/files

I expected that the packages which were updated like `@opentelemetry/core` would be reflected in the package.json file of packages which depended on them.

**Comment by dyladan** [comment] 2021-08-31 18:40
Is there any recommendation around how to support monorepos with interdependent modules? The manifest releaser doesn't have a lot of available info or docs but the bottom of the documentation md file seems to imply that the node-workspace plugin should work for that. Do I need to do anything other than add the plugin to the config to enable it?

**Comment by bcoe** [comment] 2021-09-03 21:39
@dyladan you should be able to simply add the plugin, like this:

https://github.com/looker-open-source/sdk-codegen/blob/main/release-please-config.json#L2

See: https://github.com/googleapis/release-please/blob/master/docs/manifest-releaser.md#plugins

**Comment by dyladan** [comment] 2021-09-08 11:57
No that is not working for me. Here's the config:

https://github.com/open-telemetry/opentelemetry-js/blob/main/release-please-config.json#L3

And the PR does not update the dependencies of dependent modules.

**Comment by remarkablemark** [comment] 2021-09-15 18:46
I am also experiencing release PR not updating dependent packages of Lerna monorepo

See https://github.com/little-spoon-dev/design-system/pull/12

This is my [release-please-config.json](https://github.com/little-spoon-dev/design-system/blob/master/release-please-config.json)

**Comment by bcoe** [comment] 2021-09-23 21:19
@remarkablemark was the version that was not updated a major bump? there was an issue related to this fixed last week.

**Comment by remarkablemark** [comment] 2021-09-23 23:04
> @remarkablemark was the version that was not updated a major bump? there was an issue related to this fixed last week.

@bcoe it wasn't a major bump but thanks for checking in

**Comment by phated** [comment] 2021-09-28 16:46
@remarkablemark it looks like it wasn't a major bump, but you don't use semver versioning, so lerna would have had nothing to bump. The change that @bcoe mentioned forces linking across all local projects, so it should solve your issue.

**Comment by remarkablemark** [comment] 2021-10-01 17:36
@phated how do I use semver versioning? In my project, I'm using Lerna independent versioning + [Conventional Commits](https://www.conventionalcommits.org/)

I also created a separate repo that has the same behavior as the other project: https://github.com/remarkablemark/release-please-manifest-demo

**Comment by phated** [comment] 2021-10-01 19:46
@remarkablemark A quick scan of your demo repo seems to indicate the problem is that you don't actually have a root package.json that defines your workspaces. This would mean that RP wouldn't be able to link together your monorepo dependencies.

**Comment by remarkablemark** [comment] 2021-10-01 19:49
@phated you are right, that was a bad example. The other project did have a root package.json since it uses Lerna + Yarn workspaces. However, I have removed Release Please from the project.

**Comment by bcoe** [comment] 2021-10-04 15:27
@dyladan I'm getting a 404 with the config you shared, are you still blocked?

**Comment by phated** [comment] 2021-10-04 22:24
@bcoe looks like RP was removed from that repo too.

**Comment by dyladan** [comment] 2021-11-05 19:39
Yeah we removed it from the repo. We're still using it in another repo with less interdependent modules and haven't had a problem yet, but I think it's not because it is working but just because the modules are isolated.

**Comment by bcoe** [comment] 2021-11-08 16:28
@dyladan closing for now, as we're in the middle of a big refactor, and there's a good chance this issue will have been solved ... and replaced with interesting new bugs :laughing:

**Comment by bcoe** [comment] 2021-11-08 16:28
If you do have a specific repo you would like us to dig into, don't hesitate to open a new issue.

**Closed** 2021-11-08 16:27 UTC
Labels: type: feature request
