### ISSUE TITLE
Release notes duplication in new PR design.

### ISSUE THREAD

**Issue by ddixit14** [googleapis/release-please#1718] opened 2022-10-21 12:02 UTC
Release:please seems to be populating old release notes in the new release PR, though the versions being suggested are new. 
Reference: 
1. Latest release:main [PR](https://github.com/googleapis/google-cloud-java/pull/8655) (to be released)
2. Previous release:main [PR](https://github.com/googleapis/google-cloud-java/pull/8623) (already released)

**Comment by suztomo** [comment] 2022-10-21 20:24
In the "Previous release:main [PR](https://github.com/googleapis/google-cloud-java/pull/8623) (already released)" It seems the old note is gone because these release pull requests always point to https://github.com/googleapis/google-cloud-java/blob/release-please--branches--main--release-notes/release-notes.md (by design).

<img width="930" alt="Screen Shot 2022-10-21 at 4 23 27 PM" src="https://user-images.githubusercontent.com/28604/197282608-50979b9e-4679-4f11-b875-3a0d4149819c.png">

**Comment by ddixit14** [comment] 2022-10-22 02:10
Yeah, this branch will be re-used to store the release notes for every release of main branch. 
For more context about the issue: As you can see below, the version suggested is new but release notes are the same.

These are the release notes for previous (already released) version.

![image](https://user-images.githubusercontent.com/90280028/197313566-b738d9d3-5396-4633-9a91-131f11242108.png)
----------------------------------------------------------------------------------------------------------------------
These are the release notes for the current (to-be-released) version.

![image](https://user-images.githubusercontent.com/90280028/197313660-17f5aa1b-c953-4b8b-9e63-3cc26d9add7c.png)

**Comment by suztomo** [comment] 2022-10-22 02:31
Nice screenshots.

**Comment by suztomo** [comment] 2022-10-26 18:14
Log from `release-please release-pr --token=$TOKEN --repo-url https://github.com/googleapis/google-cloud-java --dry-run --trace`: http://gpaste/6224127928041472 (only first 574 lines) showing the suspicious messages below:

```
⚠ Expected 142 releases, only found 0
⚠ Missing 142 paths: gapic-libraries-bom,google-cloud-jar-parent,google-cloud-pom-parent,java-accessapproval,java-accesscontextmanager,java-aiplatform,java-analytics-admin,java-analytics-data,java-analyticshub,java-api-gateway,java-apigee-connect,java-apigee-registry,java-apikeys,java-appengine-admin,java-area120-tables,java-artifact-registry,java-asset,java-assured-workloads,java-automl,java-bare-metal-solution,java-batch,java-beyondcorp-appconnections,java-beyondcorp-appconnectors,java-beyondcorp-appgateways,java-beyondcorp-clientconnectorservices,java-beyondcorp-clientgateways,java-bigqueryconnection,java-bigquery-data-exchange,java-bigquerydatapolicy,java-bigquerydatatransfer,java-bigquerymigration,java-bigqueryreservation,java-billingbudgets,java-billing,java-binary-authorization,java-certificate-manager,java-channel,java-cloudbuild,java-cloudcommerceconsumerprocurement,java-compute,java-contact-center-insights,java-containeranalysis,java-container,java-contentwarehouse,java-datacatalog,java-dataflow,java-dataform,java-data-fusion,java-datalabeling,java-dataplex,java-dataproc-metastore,java-dataproc,java-datastream,java-debugger-client,java-deploy,java-dialogflow-cx,java-dialogflow,java-discoveryengine,java-distributedcloudedge,java-dlp,java-dms,java-dns,java-document-ai,java-domains,java-enterpriseknowledgegraph,java-errorreporting,java-essential-contacts,java-eventarc,java-eventarc-publishing,java-filestore,java-functions,java-game-servers,java-gke-backup,java-gke-connect-gateway,java-gkehub,java-gke-multi-cloud,java-grafeas,java-gsuite-addons,java-iam-admin,java-iamcredentials,java-ids,java-iot,java-kms,java-language,java-life-sciences,java-managed-identities,java-mediatranslation,java-memcache,java-monitoring-dashboards,java-monitoring,java-networkconnectivity,java-network-management,java-network-security,java-notebooks,java-notification,java-optimization,java-orchestration-airflow,java-orgpolicy,java-os-config,java-os-login,java-phishingprotection,java-policy-troubleshooter,java-private-catalog,java-profiler,java-publicca,java-recaptchaenterprise,java-recommendations-ai,java-recommender,java-redis,java-resourcemanager,java-resource-settings,java-retail,java-run,java-scheduler,java-secretmanager,java-securitycenter,java-securitycenter-settings,java-security-private-ca,java-service-control,java-servicedirectory,java-service-management,java-service-usage,java-shell,java-speech,java-storage-transfer,java-talent,java-tasks,java-texttospeech,java-tpu,java-trace,java-translate,java-video-intelligence,java-video-live-stream,java-video-stitcher,java-video-transcoder,java-vision,java-vmmigration,java-vpcaccess,java-webrisk,java-websecurityscanner,java-workflow-executions,java-workflows
```


```
⚠ Expected 142 releases, only found 0
✔ Collecting commits since all latest releases
❯ commit search depth: 500
❯ Set(0) {}
❯ Fetching merge commits on branch main with cursor: undefined
✔ PR #8680 has many files, backfilling
```

I will upload a full log once the command finishes.

**Comment by suztomo** [comment] 2022-10-26 18:53
Full log: [release-please.log](https://github.com/googleapis/release-please/files/9872917/release-please.log)

**Comment by suztomo** [comment] 2022-10-26 21:12
Jeff found that it was looking for wrong tag by looking at "SNAPSHOT" versions written in .release-please-manifest.json file.

**Comment by suztomo** [comment] 2022-10-27 14:39
I merged https://github.com/googleapis/google-cloud-java/pull/8691 . Release Please does not update the release pull request:  https://github.com/googleapis/google-cloud-java/pull/8686

I ran the cli: [release-please.log](https://github.com/googleapis/release-please/files/9880380/release-please.log)

I think these lines below are the improvement by removing snapshot version from 

```
✔ Collecting release commit SHAs
❯ release search depth: 400
❯ Fetching releases with cursor undefined
❯ Found release for path java-workflows, google-cloud-workflows-v2.5.0
❯ Found release for path java-workflow-executions, google-cloud-workflow-executions-v2.5.0
❯ Found release for path java-websecurityscanner, google-cloud-websecurityscanner-v2.5.0
...
```

Suspicious parts:

```
...
⚠ Found release tag with component '', but not configured in manifest
⚠ Found release tag with component '', but not configured in manifest
❯ Fetching releases with cursor Y3Vyc29yOnYyOpK5MjAxNy0wMi0xNFQxMzoxMzowMC0wNTowMM4AU0Sb
⚠ Expected 142 releases, only found 141
⚠ Missing 1 paths: java-notification
❯ looking for tagName: google-cloud-notification-v0.123.20-beta
⚠ Expected 142 releases, only found 141
❯ release for path: java-workflows, version: 2.5.0, sha: b2a5f7207e9f9b2f933e75ef4fd44973a234326f
```

```
❯ release for path: gapic-libraries-bom, version: 0.2.0, sha: b2a5f7207e9f9b2f933e75ef4fd44973a234326f
✔ Collecting commits since all latest releases
❯ commit search depth: 500
❯ Set(1) { 'b2a5f7207e9f9b2f933e75ef4fd44973a234326f' }
❯ Fetching merge commits on branch main with cursor: undefined
✔ PR #8680 has many files, backfilling
❯ Backfilling file list for commit: e7742a01d98020e25d60969699f208e871bef536
❯ Found 1000 files
✔ PR #8655 has many files, backfilling
```

```
TypeError: Cannot read properties of undefined (reading 'pullRequest')
    at MavenWorkspace.run (/usr/local/lib/node_modules/release-please/build/src/plugins/workspace.js:104:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Manifest.buildPullRequests (/usr/local/lib/node_modules/release-please/build/src/manifest.js:376:38)
    at async Object.handler (/usr/local/lib/node_modules/release-please/build/src/bin/release-please.js:312:34)
```

**Closed** 2022-10-28 17:17 UTC
Labels: priority: p2, type: bug

**Comment by suztomo** [comment] 2022-10-28 17:45
@chingor13 Do you observe the "Cannot read properties of undefined (reading 'pullRequest')" error in https://github.com/googleapis/release-please/issues/1718#issuecomment-1293628206 ?
